### ISSUE TITLE
why Message<T> is generic?

### ISSUE THREAD

**Issue by IvoryRubble** [tipstrade/Firebase-Cloud-Messaging-Net#3]
Sorry for silly question, but why `net.tipstrade.FCMNet.Requests.Message<T> :  where T : Notification` is generic?

**Comment by tipstrade** [comment]
It's generic, so you can send a standard (web) notification object, but also iOS or Android notifications which also contain properties specific to those OSes.

The inheritiance is done because iOS & Android share some similar properties to the web notification. The also share some similar localisation properties, hence the LocalizedNotification abstract class.

See: https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support

```c#
public class Notification {} // This is the generic notification
public abstract class LocalizedNotification : Notification{} // Abstract class that contains localisation properties
public class iOSNotification : LocalizedNotification {} // iOS specfic notification
public class AndroidNotification : LocalizedNotification {} // Android specific notification

**Comment by IvoryRubble** [comment]
Oh. It's make sense in case of different types of notifications. Thank you for reply.
